{
 "title": "Machine learning metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Binary Classification Test Data Rate ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "application__traintestrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "BankNotePredictor" }
     ]
    }
   ]
  },
  {
   "title": " Multi Classification Test Data Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__traintestrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "MNIST28Predictor" }
     ]
    }
   ]
  },
  {
   "title": " Regression Test Data Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__traintestrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "EuroPredictor" }
     ]
    }
   ]
  },
  {
   "title": "Macro Accuracy Multi classification",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__network_evaluating_result",
     "query": "SELECT \"value\" FROM \"application__network_evaluating_result\" WHERE (\"Network\" = 'MNISTPredictor') AND $timeFilter GROUP BY \"Algorithm\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "MNISTPredictor" }
     ]
    }
   ]
  },
  {
   "title": "Absolute loss Regression",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__network_evaluating_result",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "EuroPredictor" }
     ]
    }
   ]
  },
  {
   "title": "Multi Classification Training Time (MNIST 28x28)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Network",
       "operator": "=",
       "value": "MNIST(28x28) digit predictor(Multi Classification)"
      }
     ]
    }
   ]
  },
  {
   "title": "Accuracy Binary Classification ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__network_evaluating_result",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "BankNotePredictor" }
     ]
    }
   ]
  },
  {
   "title": "Binary Classification (Bank Notes) Training Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Network",
       "operator": "=",
       "value": "Bank note validity(Binary Classification)"
      }
     ]
    }
   ]
  },
  {
   "title": "Regression(Euro Predictor) Training Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "alias": "$tag_Algorithm",
     "groupBy": [
      { "params": [ "Algorithm" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Network", "operator": "=", "value": "Euro price(Regression)" }
     ]
    }
   ]
  },
  {
   "title": "Network Saving Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "$tag_Network",
     "groupBy": [
      { "params": [ "Network" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "MetricType", "operator": "=", "value": "Saving Network" }
     ]
    }
   ]
  },
  {
   "title": "Data Loading Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "alias": "$tag_Network",
     "groupBy": [
      { "params": [ "Network" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "MetricType", "operator": "=", "value": "Loading Data" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "application__current_memory_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Evaluating Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "$tag_Network",
     "groupBy": [
      { "params": [ "Network" ], "type": "tag" }
     ],
     "measurement": "application__timer",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "MetricType", "operator": "=", "value": "Evaluating Network" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "application__current_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}